blank_issues_enabled: false
contact_links:
  - name: Ask the community for help
    url: https://github.com/ScriptXeno/ScriptXeno.github.io/discussions
    about: Please ask and answer questions here.
